### ISSUE TITLE
Any plan for EXE?

### ISSUE THREAD

**Issue by Akascape** [harshkaso/Flux#2]
Why not make an executable for windows using pyinstaller/auto-py-to-exe?

Moreover, `pyfastnoisesimd` needs Microsoft Visual C++ Build Tools 14+, so it will be better if you make some independent executable program which doesn't need any installation.

**Comment by harshkaso** [comment]
At this stage, the project is still undergoing active development, and there have been significant UI changes recently (even the gifs in readme are outdated). As a result, I am focusing on ensuring stability and functionality before proceeding with creating an executable version.

However, I do plan to provide an executable once the project reaches a stable stage.
